### ISSUE TITLE
Could not resolve host: keycloak.minikube (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by theobouwman** [learnk8s/laravel-kubernetes-demo#4]
I have another service called `keycloak.minikube` which is a OAuth2 server. On the callback of that server the following error occurs:
```
Failed to get access token: cURL error 6: Could not resolve host: keycloak.minikube (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

Do you know what this is?

**Comment by keithmifsud** [comment]
HI @theobouwman ..I got your email, thanks. The error is saying that the host is not found. It can also mean that you're simply not getting an access token. I'm not sure if you are managing to attempt to retrieve a token or if the connection is failing before the attempt.

Can you share your deployment config file(s) please? Also, is the keycloak service on the same cluster?

**Comment by theobouwman** [comment]
This is my Keycloak service which works well:
```
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
      tier: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
        tier: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_LOGLEVEL
          value: "DEBUG"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secrets
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: auth-db-secrets
              key: username
        - name: DB_ADDR
          value: "auth-db"
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: username
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: password
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: keycloak.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak
          servicePort: http
```

And here is the Laravel application:
```
apiVersion: v1
kind: Service
metadata:
  name: spoedzoekers
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: spoedzoekers-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoedzoekers
spec:
  selector:
    matchLabels:
      app: spoedzoekers-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spoedzoekers-web
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: spoedzoekers
        image: registry.gitlab.com/woodyshousing/spoedzoekers
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
              name: spoedzoekers-config
        env:
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: spoedzoekers-db-secrets
              key: username
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: spoedzoekers-db-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spoedzoekers-db-secrets
              key: password
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spoedzoekers-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: spoedzoekers.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: spoedzoekers
          servicePort: http
```
with its config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spoedzoekers-config
  labels:
    name: spoedzoekers-config
data:
  APP_NAME: "Spoedzoekers"
  APP_ENV: "production"
  APP_KEY: "base64:SY3WunEo2bhATXX1BgwCU3gzr0hyCQacMM30zp30QEI="
  APP_DEBUG: "false"
  APP_URL: "http://spoedzoekers.minikube"
  LOG_CHANNEL: "stack"
  DB_CONNECTION: "pgsql"
  DB_HOST: "spoedzoekers-db"
  DB_PORT: "5432"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  MAIL_DRIVER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  KEYCLOAK_AUTHSERVERURL: "http://keycloak.minikube/auth"
  KEYCLOAK_REALM: "woodys"
  KEYCLOAK_CLIENTID: "spoedzoekers-website"
  KEYCLOAK_CLIENTSECRET: "b30843d0-5ba6-4b41-a62f-13549544ae76"
  KEYCLOAK_REDIRECTURI: "http://spoedzoekers.minikube/login/keycloak/callback"
  KEYCLOAK_ENCRYPTIONALGORITHM: ""
  KEYCLOAK_ENCRYPTIONKEYPATH: ""
  KEYCLOAK_ENCRYPTIONKEY: ""
```

And the Dockerfile I'm using for the Laravel application:
```
FROM composer:1.6.5 as build
WORKDIR /app
COPY . /app
RUN composer install

FROM php:7.1.8-apache
RUN echo "ServerName spoedzoekers" >> /etc/apache2/apache2.conf
EXPOSE 80
COPY --from=build /app /app
COPY vhost.conf /etc/apache2/sites-available/000-default.conf
RUN chown -R www-data:www-data /app && a2enmod rewrite && service apache2 restart
```
